### ISSUE TITLE
Rationalise jQuery version

### ISSUE THREAD

**Issue by 27Bslash6** [greenpeace/planet4-master-theme#109]
jQuery v3.2.1 is registered but not used in [functions.php](https://github.com/greenpeace/planet4-master-theme/blob/master/functions.php#L236), and jQuery v1.11.1 and v1.12.4 both are present in the rendered HTML

**Comment by koyan** [comment]
I would prefer to follow what the team of @mcshanea tells us.

**Comment by kirdia** [comment]
Jetpack library also queues jquery also (at least in admin), not sure which version though.

**Comment by fklein-lu** [comment]
If it all possible, use the jQuery version bundled with WordPress, because all 3rd party code is written with that version in mind.

If you do want to use another version, then you need to dequeue the Core script, and replace it with what you want. If the code is done right, WordPress and other plugins will always just enqueue a single version of jQuery.
